### ISSUE TITLE
tensorflow unavailable with python 2.7

### ISSUE THREAD

**Issue by kdbanapindi** [divyanshu-talwar/AutoImpute#7]
Hi Divyanshu,

Thank you for developing the software. I have a question about the tensrflow dependency for AutoImpute. I tired installing tensorflow using pip but kept getting the error : 
` Could not find a version that satisfies the requirement tensorflow (from versions: none)`

Could you please let me know how to get around this?

**Comment by divyanshu-talwar** [comment]
Hey,

I assume you followed the installation steps mentioned at [tensorflow's official page](https://www.tensorflow.org/install/pip?lang=python2) and you are trying to install it on a 64bit machine.

If `pip install tensorflow` doesn't work for you. You can try `pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp27-none-linux_x86_64.whl` (the url is where the tensorflow package resides).

Going blind in here since I am quite unaware of your system specifications.
Hope this helps...

Divyanshu

**Comment by divyanshu-talwar** [comment]
Hey,

I assume you followed the installation steps mentioned at [tensorflow's official page](https://www.tensorflow.org/install/pip?lang=python2) and you are trying to install it on a 64bit machine.

If `pip install tensorflow` doesn't work for you. You can try `pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.13.1-cp27-none-linux_x86_64.whl` (the url is where the tensorflow package resides).

Going blind in here since I am quite unaware of your system specific details.
Hope this helps...

Divyanshu
